'use strict';
const $=id=>document.getElementById(id);
const levels={1:{title:'พื้นฐาน',help:'จับคู่ความหมายและลักษณะสำคัญ · รอบละไม่เกิน 4 คู่',size:4},2:{title:'อาการ',help:'แยกอาการและลักษณะของโรคที่ใกล้เคียงกัน · รอบละไม่เกิน 5 คู่',size:5},3:{title:'รายละเอียด',help:'ทบทวนการตรวจ ชนิดย่อย กลไก และหัตถการ · รอบละไม่เกิน 6 คู่',size:6}};
let data,level=1,group='all',deck=[],round=[],right=[],links={},selected=null,graded=false,roundNo=0,totalCorrect=0,totalAnswered=0,drag=null,suppressClick=false;
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function pool(){return data.questions.filter(q=>q.level===level&&(group==='all'||q.group===group))}
function restart(){deck=shuffle(pool());roundNo=0;totalCorrect=0;totalAnswered=0;nextRound()}
function nextRound(){if(!data)return;const fresh=!deck.length;if(fresh)deck=shuffle(pool());round=deck.splice(0,levels[level].size);right=shuffle(round);links={};selected=null;graded=false;roundNo++;$('results').hidden=true;$('answers').replaceChildren();$('next').hidden=true;$('check').hidden=false;$('reset').disabled=false;$('feedback').textContent=fresh&&roundNo>1?'เล่นครบคลังที่เลือกแล้ว เริ่มทบทวนชุดใหม่':'';$('roundLabel').textContent=`รอบที่ ${roundNo}`;$('pool').textContent=`${round.length} คู่ · เหลือในชุดนี้ ${deck.length} ข้อ`;$('levelLabel').textContent=levels[level].title;$('levelHelp').textContent=levels[level].help;render();}
function render(){for(const [side,items] of [['left',round],['right',right]]){$(side).replaceChildren();items.forEach((q,i)=>{const card=element('button','card');card.type='button';card.dataset.id=q.id;card.dataset.side=side;card.setAttribute('aria-pressed','false');card.append(element('span','num',side==='left'?String(i+1).padStart(2,'0'):String.fromCharCode(65+i)));const inner=element('span');if(side==='left'){inner.append(element('span','name',q.disease));if(level===1&&q.english)inner.append(element('span','english',q.english));}else inner.append(element('span','answer',q.answer));card.append(inner);card.setAttribute('aria-label',`${side==='left'?'โรค':'คำตอบ'} ${side==='left'?q.disease:q.answer}`);card.addEventListener('click',()=>{if(suppressClick||graded)return;select(side,q.id)});card.addEventListener('pointerdown',e=>beginDrag(e,side,q.id));$(side).append(card)})}update();}
function select(side,id){if(selected&&selected.side!==side){link(side==='left'?id:selected.id,side==='right'?id:selected.id);selected=null}else selected=selected?.id===id&&selected.side===side?null:{side,id};update()}
function link(leftId,rightId){for(const key of Object.keys(links))if(key===leftId||links[key]===rightId)delete links[key];links[leftId]=rightId;}
function update(){document.querySelectorAll('.card').forEach(card=>{const {id,side}=card.dataset;const match=side==='left'?links[id]:Object.keys(links).find(k=>links[k]===id);const isSelected=selected?.id===id&&selected.side===side;card.classList.toggle('selected',isSelected);card.classList.toggle('linked',!!match);card.setAttribute('aria-pressed',String(!!match||isSelected));card.setAttribute('aria-disabled',String(graded));const correct=side==='left'?links[id]===id:match===id;card.classList.toggle('correct',graded&&!!match&&correct);card.classList.toggle('wrong',graded&&!!match&&!correct)});const count=Object.keys(links).length;$('connected').textContent=`${count} / ${round.length} คู่`;$('check').disabled=count!==round.length||graded;$('instruction').textContent=graded?`คะแนนสะสม ${totalCorrect} / ${totalAnswered}`:selected?'เลือกอีกฝั่งเพื่อเชื่อมคู่':'แตะโรคใหม่เพื่อเปลี่ยนคู่ได้';requestAnimationFrame(draw);}
function anchor(id,side){const card=[...$(side).children].find(el=>el.dataset.id===id);if(!card)return null;const a=card.getBoundingClientRect(),b=$('board').getBoundingClientRect();return{x:(side==='left'?a.right:a.left)-b.left,y:a.top+a.height/2-b.top}}
function path(a,b,color,dashed=false){if(!a||!b)return;const p=document.createElementNS('http://www.w3.org/2000/svg','path');const bend=Math.max(20,Math.abs(b.x-a.x)*.45);p.setAttribute('d',`M ${a.x} ${a.y} C ${a.x+bend} ${a.y}, ${b.x-bend} ${b.y}, ${b.x} ${b.y}`);if(color)p.style.stroke=color;if(dashed)p.setAttribute('stroke-dasharray','5 5');$('lines').append(p)}
function draw(){const box=$('board').getBoundingClientRect();$('lines').setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);$('lines').replaceChildren();for(const [a,b] of Object.entries(links))path(anchor(a,'left'),anchor(b,'right'),graded?(a===b?'#18806d':'#c8555a'):null);if(drag?.moved){const start=anchor(drag.id,drag.side),end={x:drag.x-box.left,y:drag.y-box.top};path(drag.side==='left'?start:end,drag.side==='left'?end:start,'#245adb',true)}}
function beginDrag(e,side,id){if(graded||e.button!==0)return;drag={side,id,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,moved:false,pointerId:e.pointerId};}
window.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;drag.x=e.clientX;drag.y=e.clientY;if(Math.hypot(drag.x-drag.startX,drag.y-drag.startY)>7){drag.moved=true;selected={side:drag.side,id:drag.id};draw();}}, {passive:true});
window.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;if(drag.moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.card');if(target&&target.dataset.side!==drag.side){link(drag.side==='left'?drag.id:target.dataset.id,drag.side==='right'?drag.id:target.dataset.id);selected=null}else selected={side:drag.side,id:drag.id};suppressClick=true;setTimeout(()=>suppressClick=false,0)}drag=null;update()});
window.addEventListener('pointercancel',()=>{drag=null;update()});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;drag=null;update()}});
window.addEventListener('resize',()=>requestAnimationFrame(draw));
new ResizeObserver(()=>requestAnimationFrame(draw)).observe($('board'));
$('reset').addEventListener('click',()=>{if(graded)return;links={};selected=null;$('feedback').textContent='ล้างเส้นแล้ว เริ่มจับคู่ได้เลย';update()});
$('check').addEventListener('click',()=>{if(graded||Object.keys(links).length!==round.length)return;graded=true;selected=null;let correct=0;round.forEach(q=>{const ok=links[q.id]===q.id;if(ok)correct++;const wrap=element('article','review');wrap.append(element('span',`state${ok?'':' bad'}`,ok?'✓ จับคู่ถูก':'✕ ลองจำคู่นี้อีกครั้ง'),element('strong',null,q.disease));if(!ok){const chosen=right.find(x=>x.id===links[q.id]);wrap.append(element('p','chosen',`คำตอบที่เลือก: ${chosen.answer}`))}wrap.append(element('p',null,`คำตอบ: ${q.answer}`));const source=data.sources.find(s=>s.id===q.group);const a=element('a',null,source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';wrap.append(a,element('small',null,`หัวข้อ ${q.section}`));$('answers').append(wrap)});totalCorrect+=correct;totalAnswered+=round.length;$('feedback').textContent=`${correct===round.length?'ครบทุกคู่!':'ตรวจแล้ว'} ได้ ${correct} / ${round.length} คะแนน · อ่านเฉลยด้านล่างได้เลย`;$('results').hidden=false;$('check').hidden=true;$('next').hidden=false;$('reset').disabled=true;update();});
$('next').addEventListener('click',()=>{nextRound();$('board').scrollIntoView({block:'start',behavior:'auto'});$('left').firstElementChild?.focus({preventScroll:true})});
document.querySelectorAll('[data-level]').forEach(button=>button.addEventListener('click',()=>{if(!data)return;level=Number(button.dataset.level);document.querySelectorAll('[data-level]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});restart()}));
$('group').addEventListener('change',()=>{if(!data)return;group=$('group').value;restart()});
fetch('questions.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(d=>{data=d;if(!Array.isArray(data.questions)||!data.questions.length)throw Error('empty');$('bankCount').textContent=data.questions.length;$('sourceCount').textContent=`${new Set(data.questions.map(q=>q.diseaseId)).size} โรค · ${data.sources.length} เอกสาร`;$('updated').textContent=`เนื้อหาล่าสุด ${data.updated}`;data.sources.forEach(s=>{const option=element('option',null,s.label);option.value=s.id;$('group').append(option);const a=element('a',null,s.title);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';$('sources').append(a)});$('schedule').textContent=data.updateSchedule||'ยังไม่ได้ตั้งการอัปเดตรายสัปดาห์';$('loading').hidden=true;restart()}).catch(()=>{$('loading').textContent='โหลดคลังคำถามไม่สำเร็จ กรุณารีเฟรชหน้าแล้วลองอีกครั้ง';$('feedback').textContent='ยังไม่สามารถเริ่มเกมได้';$('reset').disabled=true;});
