'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const letters=['ก','ข','ค','ง'];
const levelNames={1:'ง่าย',2:'ปานกลาง',3:'ยาก'};
const levelHelp={1:'ระดับอุดมศึกษา · ทบทวนพื้นฐาน นิยาม รหัส และข้อเท็จจริงที่ Lecture ระบุโดยตรง',2:'ระดับอุดมศึกษา · เชื่อมโยง เปรียบเทียบ และประยุกต์ข้อมูลจาก Lecture',3:'ระดับอุดมศึกษา · วิเคราะห์หลายเงื่อนไข รายละเอียดเชิงลึก และการตัดสินใจจาก Lecture'};
const state={data:null,level:1,topic:'all',queue:[],index:0,score:0,answers:[],checked:false,choice:null};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selectedPool(){return state.data.questions.filter(q=>q.level===state.level&&(state.topic==='all'||q.source===state.topic));}
function start(){state.queue=shuffle(selectedPool());state.index=0;state.score=0;state.answers=[];state.checked=false;state.choice=null;$('#results').hidden=true;$('#score').textContent='0 คะแนน';render();}
function buildTopics(){const select=$('#topic');const sourceIds=[...new Set(state.data.questions.map(q=>q.source))];sourceIds.forEach(id=>{const s=state.data.sources.find(x=>x.id===id);if(!s)return;const o=document.createElement('option');o.value=id;o.textContent=s.label||s.title;select.appendChild(o)});}
function render(){const q=state.queue[state.index];$('#levelLabel').textContent=levelNames[state.level];$('#levelHelp').textContent=levelHelp[state.level];if(!q){$('#questionWrap').innerHTML='<div class="review"><strong>ยังไม่มีคำถามในตัวกรองนี้</strong><p>ลองเลือก “รวมทุก Lecture” หรือเลือกระดับอื่น</p></div>';$('#check').disabled=true;$('#next').hidden=true;return;}state.checked=false;state.choice=null;$('#feedback').textContent='';$('#feedback').className='';$('#check').hidden=false;$('#next').hidden=true;$('#check').disabled=true;$('#progress').textContent=`ข้อ ${state.index+1} / ${state.queue.length}`;const source=state.data.sources.find(s=>s.id===q.source);$('#questionWrap').innerHTML=`<article class="question-card"><div class="q-meta"><span class="q-type">ปรนัย 4 ตัวเลือก</span><span class="q-source">${esc(source?.label||source?.title||q.source)}</span></div><h2>${esc(q.prompt)}</h2><div class="option-list">${q.options.map((o,i)=>`<button class="option-btn" data-choice="${i}"><span class="option-key">${letters[i]}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="source-note"><strong>Source:</strong> ${esc(source?.title||q.source)}</div></article>`;$$('.option-btn').forEach(b=>b.addEventListener('click',()=>{if(state.checked)return;state.choice=Number(b.dataset.choice);$$('.option-btn').forEach(x=>x.classList.toggle('selected',x===b));$('#check').disabled=false;}));}
function evaluate(){if(state.checked||state.choice===null)return;const q=state.queue[state.index];const ok=state.choice===q.answer;state.checked=true;if(ok)state.score++;state.answers.push({prompt:q.prompt,ok,chosen:q.options[state.choice],correct:q.options[q.answer],explanation:q.explanation,source:q.source});$$('.option-btn').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===state.choice&&i!==q.answer)b.classList.add('wrong')});$('#score').textContent=`${state.score} คะแนน`;$('#feedback').textContent=(ok?'ถูกต้อง · ':'ยังไม่ถูก · ')+q.explanation;$('#feedback').className=ok?'good':'bad';$('#check').hidden=true;$('#next').hidden=false;$('#next').textContent=state.index===state.queue.length-1?'ดูสรุป →':'ข้อต่อไป →';}
function next(){if(state.index<state.queue.length-1){state.index++;render();$('#questionWrap').scrollIntoView({block:'start',behavior:'auto'});}else finish();}
function finish(){const total=state.queue.length,pct=total?Math.round(state.score/total*100):0;$('#questionWrap').innerHTML='<div class="review"><strong>จบชุดแบบทดสอบแล้ว</strong><p>ดูคะแนนและทบทวนคำตอบด้านล่าง</p></div>';$('#check').hidden=true;$('#next').hidden=true;$('#summary').innerHTML=`<div class="score-big">${state.score}/${total}<span>${pct}% · ระดับ${levelNames[state.level]}</span></div>`;$('#reviewList').innerHTML=state.answers.map(a=>{const s=state.data.sources.find(x=>x.id===a.source);return `<div class="review"><span class="state ${a.ok?'':'bad'}">${a.ok?'ตอบถูก':'ทบทวนอีกครั้ง'}</span><p class="prompt">${esc(a.prompt)}</p>${a.ok?'':`<p class="chosen">คำตอบของคุณ: ${esc(a.chosen)}</p>`}<p class="answer-line"><strong>เฉลย:</strong> ${esc(a.correct)}</p><p>${esc(a.explanation)}</p><small class="source-line">Source: ${esc(s?.title||a.source)}</small></div>`}).join('');$('#results').hidden=false;$('#results').scrollIntoView({behavior:'smooth',block:'start'});}
async function init(){try{const body=document.body,bank=body.dataset.bank;if(!bank)throw new Error('ไม่พบคลังคำถาม');const res=await fetch(`${bank}?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`โหลดคลังคำถามไม่สำเร็จ (HTTP ${res.status})`);state.data=await res.json();if(!Array.isArray(state.data.questions)||!state.data.questions.length)throw new Error('คลังคำถามว่าง');$('#bankCount').textContent=state.data.questions.length;$('#sourceCount').textContent=`${state.data.sources.length} Lecture sources`;$('#updated').textContent=new Date(state.data.generatedAt).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'});$('#sources').innerHTML=state.data.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`).join('');buildTopics();start();}catch(e){$('#questionWrap').innerHTML=`<div class="review"><strong>โหลดข้อมูลไม่สำเร็จ</strong><p>${esc(e.message)}</p></div>`;$('#check').disabled=true;}}
$$('.levels button').forEach(b=>b.addEventListener('click',()=>{state.level=Number(b.dataset.level);$$('.levels button').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});start();}));
$('#topic')?.addEventListener('change',e=>{state.topic=e.target.value;start();});
$('#restart')?.addEventListener('click',start);$('#check')?.addEventListener('click',evaluate);$('#next')?.addEventListener('click',next);
init();